name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53
          - arm_cortex-a7_neon-vfpv4
          - mips_24kc
          - mipsel_24kc
          - x86_64
        version:
          - '22.03.4'
          - '22.03.5'
          - '23.05.0'
          - openwrt-22.03
          - openwrt-23.05
          - main

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.version }}
          NO_DEFAULT_FEEDS: 1
          V: "s"
          PACKAGES: quectel-timesync
      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-${{ matrix.version }}-packages
          path: bin/packages
