name: Test Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53
          - arm_cortex-a7_neon-vfpv4
          - mips_24kc
          - mipsel_24kc
          - x86_64

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: |
            untrusted comment: private key 7580714ee0d0b178
            RWRCSwAAAABqaz5Tmbv63Wvk42y8YA1HjJ8fPtSeBx11gHFO4NCxeECdO33e8TvyG85V8TI2e3+gG+jFr4Nft63N6gMGEmR/rqTiIXIxplpNm1AcdEF3SsT+mfwwud+YrhLkaeBpu3c=
          NO_DEFAULT_FEEDS: 1
          V: "s"
      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk
